openapi: 3.0.3
info:
  description: Slug Finance API
  version: 0.1.0
  title: Finance API
servers:
  - url: /
paths:
  '/v0/ticker/':
    parameters:
      - name: id
        in: query
        description: Stock Ticker
        required: true
        schema:
          type: string
          format: string
    get:
      description: Returns the email identified by the id
      responses:
        '200':
          description: Email found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Stock'
        '404':
          description: Stock ticker not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/v0/retrieveInfo/':
    parameters:
      - name: id
        in: query
        description: Stock Ticker
        required: true
        schema:
          type: string
          format: string
    get:
      description: Returns the email identified by the id
      responses:
        '200':
          description: Email found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Stock'
        '404':
          description: Stock ticker not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/v0/getDescription':
    parameters:
      - name: id
        in: query
        description: Stock Name
        required: true
        schema:
          type: string
          format: string
    get:
      description: Grab about me for stock
      responses:
        '200':
          description: Stock Found
          content: 
            application/json:
              schema:
                type: string
        '404':
          description: Stock ticker not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/v0/getInfo':
    post:
      description: Get Information
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockTicker'
      responses:
        '201':
          description: response
          content:
            application/json:
              schema:
                type: string
  '/v0/login':
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: book response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  '/v0/create':
    post:
      description: Create
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '201':
          description: server response saying its created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  '/v0/add':
    post:
      description: Add Stock to Database
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StockTicker'
      responses:
        '201':
          description: added to database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
  '/v0/view':
    parameters:
      - name: id
        in: query
        description: Stock Ticker
        required: true
        schema:
          type: string
          format: string
    get:
      description:
      responses:
        '200':
          description: Stock table found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Stock'     
  '/v0/getHistory':
    post:
      description:
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticker'
            examples:
              Day:
                value:
                  ticker: TSLA
                  year: 2022
                  month: 1
                  day: 1
                  year2: 2022
                  month2: 2
                  day2: 1
                  interval: 1d
              Week:
                value:
                  ticker: TSLA
                  year: 2022
                  month: 1
                  day: 1
                  year2: 2022
                  month2: 2
                  day2: 1
                  interval: 1wk
              Month:
                value:
                  ticker: TSLA
                  year: 2022
                  month: 1
                  day: 1
                  year2: 2022
                  month2: 2
                  day2: 1
                  interval: 1mo
                
      responses:
        '201':
          description: Historical Data found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#components/schemas/Data'


components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Stock:
      type: object
      additionalProperties: false
      required:
        - symbol
        - price
        - change
        - dailyChange
      properties:
        symbol:
          type: string
        price:
          type: string
        change:
          type: string
        dailyChange:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        accessToken:
          type: string
      required:
        - name
        - accessToken      
    Credentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
    Ticker:
      type: object
      properties:
        ticker:
          type: string
        year:
          type: integer
        month:
          type: integer
        day:
          type: integer
        year2:
          type: integer
        month2:
          type: integer
        day2:
          type: integer
        interval:
          type: string
    Data:
      type: object
      properties:
        ticker:
          type: string
        data:
          type: object
    StockTicker:
      type: object
      properties:
        ticker:
          type: string